security:
  oauth2:
    client:
      clientId: my-client
      clientSecret: 34486f3c-d419-4daf-9308-64fafa9e6dce
    resource:
      user-info-uri: http://localhost:32768/auth/realms/demo/protocol/openid-connect/userinfo
      token-info-uri: http://localhost:32768/auth/realms/demo/protocol/openid-connect/token/introspect
      prefer-token-info: true
